name: Maven Build
description: Run a Maven Build

inputs:
  build-command:
    description: The Maven command to build the project. The default is `package`.
    required: false
    type: string
    default: package
  run-tests:
    description: Whether or not to run tests. The default is true.
    required: false
    type: boolean
    default: true

runs:
  using: "composite"
  steps:
    - name: Set up JDK 17 for x64
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        architecture: x64
        cache: maven
    - name: Build with Maven
      shell: bash
      run: mvn -s settings.xml -B -U clean ${{ inputs.build-command }}${{ inputs.run-tests && '' || ' -DskipTests'  }}
