name: PR Checks

on:
  workflow_dispatch:
  pull_request:

jobs:
  build-on-ubuntu:
    name: Maven Build on Ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/workflows/maven-build.yml
  
  build-on-windows:
    name: Maven Build on Windows
    runs-on: windows-latest
    steps:
    - uses: ./.github/workflows/maven-build.yml
