name: License Scanning for Maven

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'pom.xml'
      - '.github/workflows/license-scanning.yml'
  pull_request:
    paths:
      - 'pom.xml'
      - '.github/workflows/license-scanning.yml'

# Cancel previous jobs
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  ALLOW_LICENSES: "licenses/license/name!='The Apache Software License, Version 2.0' and licenses/license/name!='Apache License, Version 2.0' and licenses/license/name!='BSD' and licenses/license/name!='BSD-style license'"
  REPORT_PATH: "target/generated-resources"

jobs:
  fetch-licenses:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install XQ
      run: pip install xq
    - uses: ./.github/actions/maven-build
      with:
        build-command: install
        run-tests: false
    - name: License XML report
      run: mvn org.codehaus.mojo:license-maven-plugin:2.4.0:aggregate-download-licenses
    - name: Validate XML report
      run: |
        LICENSE_REPORT=`xq "//dependency[licenses/license/name!=${{ env.ALLOW_LICENSES }}]" ./${{ env.REPORT_PATH }}/licenses.xml`
        LINES_FOUND=`echo "$LICENSE_REPORT" | wc -l`
        if [ $LINES_FOUND -gt 1 ]; then echo "License issues found ..." ; echo $LICENSE_REPORT ; exit -1; fi
    - name: Upload license reports
      uses: actions/upload-artifact@v4
      with:
        name: license-reports
        path: '**/${{ env.REPORT_PATH }}/'
    - name: Upload license XML reports
      uses: actions/upload-artifact@v4
      with:
        name: license-xml-reports
        path: '**/${{ env.REPORT_PATH }}/licenses.xml'
