name: Maven Build

inputs:
  run-tests:
    required: false
    default: true
    type: boolean

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17 for x64
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        architecture: x64
        cache: maven
    - name: Build with Maven
      run: mvn -B -U clean package${{ inputs.run-tests && ' --DskipTests' || ''  }}
